### ISSUE TITLE
numeric argument integrity is not check

### ISSUE THREAD

**Issue by alcortesm** [alcortesm/AllBase#3]
``` text
; python3 allbase.py fasdf
Traceback (most recent call last):
  File "allbase.py", line 41, in <module>
    main()
  File "allbase.py", line 37, in main
    print(to_bases(int(args.number, 10)))
ValueError: invalid literal for int() with base 10: 'fasdf'
```

**Comment by alcortesm** [comment]
``` text
; python3 -m allbase asdf
need a positive integer, got 'asdf'
```
